import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/Components/common/navbar/page.jsx";
import ReduxProvider from "@/Utils/Providers/reduxProvider";
import ReactQueryProvider from "@/Utils/Providers/reactQueryProvider";
import AppInitializer from "@/Utils/Providers/appInitializer";
import RouteGuard from "@/Services/routeGuard";
import GlobalModal from "@/Components/chadcn-ui/modal/customizableModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Get Offer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <ReactQueryProvider>
            <AppInitializer>
              <RouteGuard>
                <Navbar />
                {children}
                <GlobalModal />
              </RouteGuard>
            </AppInitializer>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
