import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/Components/navbar/page.jsx";
import { FBFooter } from "@/Components/footer/page.jsx";
import ReduxProvider from "@/Utils/Providers/reduxProvider";
import ReactQueryProvider from "@/Utils/Providers/reactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>

        <ReactQueryProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Navbar />
            {children}
            <FBFooter />

          </body>
        </ReactQueryProvider>
      </ReduxProvider>
    </html>
  );
}
